### PR TITLE
Milestone 3

### PR DESCRIPTION
**Pull request by IBTechRaj**
Milestone-3 requirements fulfilled.
Submitted for code review.

### CODE REVIEW

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
**Status: Changes Required**

Hello @IBTechRaj ✋ 

Nice work but you have to make some changes in order to get approval.

- [ ] Please fix linter errors and You do not need to use both configuration for linter.

- [ ] Display component should  accepts the result of the calculation as an incoming prop  [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/incomingProps.png) and use div instead of input tag.

- [ ] Display component result prop should be a String with default value = 0   [should be String screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)   [default props screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png)

- [ ] Display should take 100% width.

Please fix those issues and submit another request.

Happy Coding
Adnan Afsari

**Comment by IBTechRaj** [comment]
Made the corrections suggested.
Submitted for rereview of code.

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @IBTechRaj   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**KIndly fix your linter's error according to the previous reviewer.**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @IBTechRaj , 

### [changes required]

This branch is reporting git conflicts...please resolve them and file for last re-review....

Syrry about that
git

**Comment by IBTechRaj** [comment]
This branch has run into conflicts and also I was not able to run Stylelint errors. After chat with Shey Louis (attached) I installed Stylelint extension in VSCode. To resolve file conflict, Github instructions are leading me to merge this branch with development. I cleared all the errors pointed out in the first review of this branch.  

I may be permitted to merge this branch. 
Thank you
[CalcMilestone-3Chat.txt](https://github.com/IBTechRaj/ReactCalculator/files/4799483/CalcMilestone-3Chat.txt)

**Review by bellom — APPROVED** [review]
Hi @IBTechRaj 

**I can see your effort every time you push, You have done well.
Note: Take not of conflicts in your next milestone and also in your next project.**

### LET'S MOVE TO THE NEXT MILESTONE 👍 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
